spring:
  application:
    name: payments
  datasource:
    url: jdbc:postgresql://localhost:5471/payments
    username: vencer
    password: vencer
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Ok para dev, troque para 'validate' ou 'none' em produção
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#    open-in-view: false  # Recomendado para evitar problemas de performanc