spring:
  application:
    name: payments
  datasource:
    url: jdbc:postgresql://localhost:5490/payments
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect